import Head from 'next/head'
import { useQuery } from '@tanstack/react-query'

const fetcher = async () => (await fetch('/api/hello')).json()

export default function Home() {
	const { isLoading, data: member } = useQuery(['hello'], fetcher)

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>{isLoading ? 'Loading...' : member?.name}</main>
		</>
	)
}
